# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            skyeyvapor's Tech Note
tagline:          'A Jekyll theme'
description:      'Notes, articles and experiences of my computer science learning paths.'
url:              http://skyeyvapor.github.io
baseurl:          /

author:
  name:           'Ching-Lan Chen'
  url:            https://twitter.com/skyeyvapor

paginate:         5


# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/skyeyvapor

# Gems
gems:             [jekyll-paginate]