# Dependencies
#markdown:         kramdown
#highlighter:      rouge
#gems:             [jekyll-paginate]

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

# Permalinks  Permalink 影響著部落格文章網址的顯示方式，Jekyll 提供三種選擇：
permalink:        pretty

# Setup
title:            skyeyvapor's Tech Note
tagline:          "skyeyvapor's github io" 
description:      'Notes, articles and experiences of my computer science learning paths.'
url:              http://skyeyvapor.github.io  # 放在github上要/才能css找的到
baseurl: "" # the subpath of your site, e.g. /blog
author:  'Ching-Lan Chen'
name:             'Ching-Lan Chen'
url:              https://twitter.com/skyeyvapor

paginate:         5


# Custom vars

repo:             https://github.com/skyeyvapor
github_username:  skyeyvapor
instagram_username:      skyeyvapor  
